version: '3'

services:
  neo4j:
    image: neo4j:enterprise
    ports:
      - "7474:7474" # 管理画面用port
      - "7687:7687" # websocket用port
    volumes:
      - ./data:/var/lib/neo4j/data
      - ./logs:/logs
      - ./conf:/conf
      - ./import:/var/lib/neo4j/import # ここにCSVファイルを配置
      - ./script:/var/lib/neo4j/script # ここに起動時実行するスクリプトを配置
      
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_dbms_default__database=$DB_name
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      # - NEO4J_dbms_default__database=latest
      # - EXTENSION_SCRIPT=script/import_csv.sh # 起動時に実行するスクリプト