version: '3'

services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474" # 管理画面用port
      - "7687:7687" # websocket用port
    volumes:
      - ./data:/data
      - ./logs:/logs
      - ./conf:/conf
      - ./import:/import # ここにCSVファイルを配置
      
    environment:
      - NEO4J_AUTH=neo4j/password
      - EXTENSION_SCRIPT=import_csv.sh # 起動時に実行するスクリプト